str = "This is the demo example of the String in Python. Python has a str type."
str1 = "1\t2\t3\t"
str2 = "#######HEllo world#############"
str3 = "   HI, I am from Canada     "
print(type(str))
print(len(str))
print(str)
print(str.upper())
print(str.lower())
print(str.capitalize())
print(str.find('the',10))
print(str.join("My name is Ankiit"))
print(str.casefold())
print(str.center(500,'#'))
print(str.count('the'))
print(str.endswith('type.'))
print(str.isnumeric())
print(str1.isdigit())
print(str1.islower())
print(str1.isupper())
print(str1.isalnum())
print(str.isalnum())
print(str.isspace())
print(str.encode())
print(str.encode("UTF-8"))
print(str.expandtabs(2))
print(str.expandtabs(3))
print(str.format())
print(str.isalpha())
print(str.isascii())
print(str.isdecimal())
print(str.isprintable())
print(str.title())
print(str1.expandtabs())
print(str.index("the"))
print(str1.isidentifier())
print(str2.lstrip("#"))
print(str2.rstrip("#"))
print(str2.replace("#","!",2))
print(str.rfind("Python"))
print(str.rindex("Python"))
print(str.rjust(500,"P"))
print(str.split("."))
print(str.splitlines(True))
print(str.swapcase())
print(str2.zfill(50))
print(str3.strip())