str = "This is the demo example of the String in Python. Python has a str type."
str1 = "123"
print(type(str))
print(len(str))
print(str)
print(str.upper())
print(str.lower())
print(str.capitalize())
print(str.find('the',10))
print(str.join("My name is Ankiit"))
print(str.casefold())
print(str.center(500,'#'))
print(str.count('the'))
print(str.endswith('type.'))
print(str.isnumeric())
print(str1.isdigit())
print(str1.islower())
print(str1.isupper())
print(str1.isalnum())
print(str.isalnum())
print(str.isspace())
print(str.encode())
print(str.encode("UTF-8"))
print(str.expandtabs(2))
print(str.expandtabs(3))
print(str.format())
print(str.isalpha())
print(str.isascii())
print(str.isdecimal())
print(str.isprintable())
print(str.title())
